version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.7-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  fluentbit:
    container_name: fluent-bit-rabbitmq-output
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
  
volumes:
  rabbitmq-data: